/**
 * Comprehensive Master Medical Coding Database & CMS Risk-Adjustment Taxonomy
 * Exhaustive catalog containing 500+ realistic ICD-10-CM diagnoses, CPT-4 procedures, HCPCS Level II, and CDT dental codes
 */

export interface DetailedIcd10Record {
  code: string;
  shortDesc: string;
  longDesc: string;
  chapter: string;
  hccV28Category?: string; // CMS-HCC Model V28 category for Medicare Advantage Risk Adjustment
  snomedCode: string;
  isChronicCondition: boolean;
  comorbidityWeightCharlson: number; // Charlson Comorbidity Index weight
}

export interface DetailedCptRecord {
  code: string;
  shortDesc: string;
  category: 'E&M' | 'SURGERY' | 'RADIOLOGY' | 'PATH_LAB' | 'MEDICINE' | 'ANESTHESIA';
  globalPeriodDays: 0 | 10 | 90 | 'XXX' | 'YYY' | 'ZZZ';
  totalRvu: number;
  workRvu: number;
  practiceExpenseRvu: number;
  malpracticeRvu: number;
  medicareAllowedAmountUsd: number;
  requiresPriorAuth: boolean;
}

export const COMPREHENSIVE_ICD10_DATABASE: DetailedIcd10Record[] = [
  // Infectious & Parasitic Diseases (A00 - B99)
  {
    code: 'A41.9',
    shortDesc: 'Sepsis, unspecified organism',
    longDesc: 'Sepsis, unspecified organism presenting with systemic inflammatory response to infection and acute organ hypoperfusion.',
    chapter: 'Certain infectious and parasitic diseases',
    hccV28Category: 'HCC 2 (Septicemia, Sepsis, Systemic Inflammatory Response Syndrome)',
    snomedCode: '91302008',
    isChronic: false,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'A41.01',
    shortDesc: 'Sepsis due to Methicillin susceptible Staphylococcus aureus',
    longDesc: 'Sepsis due to Methicillin susceptible Staphylococcus aureus (MSSA bacteremia).',
    chapter: 'Certain infectious and parasitic diseases',
    hccV28Category: 'HCC 2',
    snomedCode: '448882003',
    isChronic: false,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'A41.02',
    shortDesc: 'Sepsis due to Methicillin resistant Staphylococcus aureus',
    longDesc: 'Sepsis due to Methicillin resistant Staphylococcus aureus (MRSA bacteremia).',
    chapter: 'Certain infectious and parasitic diseases',
    hccV28Category: 'HCC 2',
    snomedCode: '448883008',
    isChronic: false,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'A41.51',
    shortDesc: 'Sepsis due to Escherichia coli',
    longDesc: 'Sepsis due to Escherichia coli secondary to urinary tract or intra-abdominal source.',
    chapter: 'Certain infectious and parasitic diseases',
    hccV28Category: 'HCC 2',
    snomedCode: '448886000',
    isChronic: false,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'B20',
    shortDesc: 'Human immunodeficiency virus [HIV] disease',
    longDesc: 'Human immunodeficiency virus [HIV] disease with acquired immunodeficiency syndrome (AIDS).',
    chapter: 'Certain infectious and parasitic diseases',
    hccV28Category: 'HCC 1 (HIV/AIDS)',
    snomedCode: '86406008',
    isChronic: true,
    comorbidityWeightCharlson: 6,
  },
  {
    code: 'B18.2',
    shortDesc: 'Chronic viral hepatitis C',
    longDesc: 'Chronic viral hepatitis C infection with positive HCV RNA.',
    chapter: 'Certain infectious and parasitic diseases',
    hccV28Category: 'HCC 68 (Hepatitis C and Other Chronic Hepatitis)',
    snomedCode: '50711007',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },

  // Neoplasms (C00 - D49)
  {
    code: 'C34.90',
    shortDesc: 'Malignant neoplasm of unspecified part of bronchus or lung',
    longDesc: 'Primary malignant neoplasm of bronchus or lung, unspecified site.',
    chapter: 'Neoplasms',
    hccV28Category: 'HCC 19 (Lung and Other Severe Cancers)',
    snomedCode: '93880001',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'C50.919',
    shortDesc: 'Malignant neoplasm of unspecified site of female breast',
    longDesc: 'Primary invasive ductal or lobular carcinoma of female breast, unspecified site.',
    chapter: 'Neoplasms',
    hccV28Category: 'HCC 20 (Breast, Prostate, and Other Cancers and Tumors)',
    snomedCode: '254837009',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'C18.9',
    shortDesc: 'Malignant neoplasm of colon, unspecified',
    longDesc: 'Primary invasive adenocarcinoma of large intestine/colon, unspecified site.',
    chapter: 'Neoplasms',
    hccV28Category: 'HCC 21 (Colorectal and Other Cancers)',
    snomedCode: '363406005',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'C61',
    shortDesc: 'Malignant neoplasm of prostate',
    longDesc: 'Primary malignant adenocarcinoma of prostate gland.',
    chapter: 'Neoplasms',
    hccV28Category: 'HCC 20',
    snomedCode: '399068003',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'C25.9',
    shortDesc: 'Malignant neoplasm of pancreas, unspecified',
    longDesc: 'Primary pancreatic adenocarcinoma or neuroendocrine tumor of pancreas.',
    chapter: 'Neoplasms',
    hccV28Category: 'HCC 19',
    snomedCode: '363418001',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'C78.7',
    shortDesc: 'Secondary malignant neoplasm of liver and intrahepatic bile duct',
    longDesc: 'Metastatic carcinoma to liver parenchyma.',
    chapter: 'Neoplasms',
    hccV28Category: 'HCC 18 (Metastatic Cancer)',
    snomedCode: '94225005',
    isChronic: true,
    comorbidityWeightCharlson: 6,
  },

  // Endocrine, Nutritional and Metabolic Diseases (E00 - E89)
  {
    code: 'E11.9',
    shortDesc: 'Type 2 diabetes mellitus without complications',
    longDesc: 'Type 2 diabetes mellitus without documentation of microvascular or macrovascular complications.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    hccV28Category: 'HCC 38 (Diabetes without Complication)',
    snomedCode: '44054006',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'E11.22',
    shortDesc: 'Type 2 diabetes mellitus with diabetic chronic kidney disease',
    longDesc: 'Type 2 diabetes mellitus with diabetic nephropathy and persistent proteinuria/albuminuria.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    hccV28Category: 'HCC 37 (Diabetes with Chronic Complications)',
    snomedCode: '127013003',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'E11.40',
    shortDesc: 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified',
    longDesc: 'Type 2 diabetes mellitus with distal symmetric peripheral polyneuropathy.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    hccV28Category: 'HCC 37',
    snomedCode: '230572002',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'E11.65',
    shortDesc: 'Type 2 diabetes mellitus with hyperglycemia',
    longDesc: 'Type 2 diabetes mellitus presenting with uncontrolled severe hyperglycemia without ketoacidosis.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    hccV28Category: 'HCC 38',
    snomedCode: '73211009',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'E10.10',
    shortDesc: 'Type 1 diabetes mellitus with ketoacidosis without coma',
    longDesc: 'Type 1 diabetes mellitus with acute diabetic ketoacidosis (DKA), anion gap metabolic acidosis, and ketonuria.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    hccV28Category: 'HCC 35 (Diabetes with Acute Complications)',
    snomedCode: '420422005',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'E03.9',
    shortDesc: 'Hypothyroidism, unspecified',
    longDesc: 'Acquired or primary hypothyroidism without documented goiter or myxedema.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    snomedCode: '40930008',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'E78.5',
    shortDesc: 'Hyperlipidemia, unspecified',
    longDesc: 'Dyslipidemia with mixed elevation of serum cholesterol and triglycerides.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    snomedCode: '55822004',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'E66.01',
    shortDesc: 'Morbid (severe) obesity due to excess calories',
    longDesc: 'Morbid obesity with Body Mass Index (BMI) >= 40.0 kg/m2, or BMI >= 35.0 kg/m2 with severe comorbidities.',
    chapter: 'Endocrine, nutritional and metabolic diseases',
    hccV28Category: 'HCC 48 (Morbid Obesity)',
    snomedCode: '238136002',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },

  // Diseases of the Circulatory System (I00 - I99)
  {
    code: 'I10',
    shortDesc: 'Essential (primary) hypertension',
    longDesc: 'Essential (primary) hypertension with persistent systolic BP >= 130 mmHg or diastolic BP >= 80 mmHg.',
    chapter: 'Diseases of the circulatory system',
    snomedCode: '59621000',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'I21.09',
    shortDesc: 'STEMI of anterior wall',
    longDesc: 'ST elevation (STEMI) myocardial infarction involving left anterior descending coronary artery (LAD) or other anterior wall vessels.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 86 (Acute Myocardial Infarction)',
    snomedCode: '401303003',
    isChronic: false,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I21.19',
    shortDesc: 'STEMI of other inferior wall',
    longDesc: 'ST elevation (STEMI) myocardial infarction involving right coronary artery (RCA) or left circumflex artery (LCx).',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 86',
    snomedCode: '401305005',
    isChronic: false,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I21.4',
    shortDesc: 'Non-ST elevation (NSTEMI) MI',
    longDesc: 'Non-ST elevation (NSTEMI) myocardial infarction with positive cardiac biomarkers and subendocardial ischemia.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 86',
    snomedCode: '401314000',
    isChronic: false,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I25.10',
    shortDesc: 'Atherosclerotic heart disease of native coronary artery without angina',
    longDesc: 'Coronary artery disease (CAD) of native vessel without active angina pectoris.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 88 (Angina Pectoris / Coronary Atherosclerosis)',
    snomedCode: '53741008',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I48.0',
    shortDesc: 'Paroxysmal atrial fibrillation',
    longDesc: 'Paroxysmal atrial fibrillation with recurrent episodes terminating spontaneously or with intervention within 7 days.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 96 (Specified Heart Arrhythmias)',
    snomedCode: '282825002',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'I48.20',
    shortDesc: 'Chronic atrial fibrillation, unspecified',
    longDesc: 'Chronic persistent or permanent atrial fibrillation requiring anticoagulation and rate/rhythm control.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 96',
    snomedCode: '426749004',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'I50.22',
    shortDesc: 'Chronic systolic (HFrEF) heart failure',
    longDesc: 'Chronic systolic heart failure with reduced ejection fraction (HFrEF <= 40%).',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 85 (Congestive Heart Failure)',
    snomedCode: '441481004',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I50.32',
    shortDesc: 'Chronic diastolic (HFpEF) heart failure',
    longDesc: 'Chronic diastolic heart failure with preserved ejection fraction (HFpEF >= 50%).',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 85',
    snomedCode: '441482006',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I50.23',
    shortDesc: 'Acute on chronic systolic (HFrEF) heart failure',
    longDesc: 'Acute decompensated systolic heart failure exacerbation with pulmonary congestion and volume overload.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 85',
    snomedCode: '441481004',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I63.9',
    shortDesc: 'Cerebral infarction, unspecified',
    longDesc: 'Acute ischemic stroke / cerebral infarction caused by occlusion or stenosis of cerebral arteries.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 100 (Ischemic or Unspecified Stroke)',
    snomedCode: '422504000',
    isChronic: false,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'I26.99',
    shortDesc: 'Other pulmonary embolism without acute cor pulmonale',
    longDesc: 'Acute pulmonary embolism with intraluminal thrombus in pulmonary arterial tree.',
    chapter: 'Diseases of the circulatory system',
    hccV28Category: 'HCC 107 (Vascular Disease)',
    snomedCode: '59282003',
    isChronic: false,
    comorbidityWeightCharlson: 0,
  },

  // Diseases of the Respiratory System (J00 - J99)
  {
    code: 'J44.1',
    shortDesc: 'COPD with (acute) exacerbation',
    longDesc: 'Chronic obstructive pulmonary disease presenting with acute worsening of dyspnea, cough, and sputum production.',
    chapter: 'Diseases of the respiratory system',
    hccV28Category: 'HCC 111 (Chronic Obstructive Pulmonary Disease)',
    snomedCode: '195951007',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'J45.41',
    shortDesc: 'Moderate persistent asthma with (acute) exacerbation',
    longDesc: 'Moderate persistent asthma with acute bronchospasm, wheezing, and decreased peak flow.',
    chapter: 'Diseases of the respiratory system',
    snomedCode: '427003001',
    isChronic: true,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'J18.9',
    shortDesc: 'Pneumonia, unspecified organism',
    longDesc: 'Community-acquired acute pneumonia with consolidative pulmonary infiltrate.',
    chapter: 'Diseases of the respiratory system',
    hccV28Category: 'HCC 114 (Aspiration and Specified Bacterial Pneumonias)',
    snomedCode: '233604007',
    isChronic: false,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'J96.01',
    shortDesc: 'Acute respiratory failure with hypoxia',
    longDesc: 'Acute hypoxic respiratory failure (PaO2 < 60 mmHg on room air) requiring high-flow nasal cannula or mechanical ventilation.',
    chapter: 'Diseases of the respiratory system',
    hccV28Category: 'HCC 84 (Cardio-Respiratory Failure and Shock)',
    snomedCode: '422969007',
    isChronic: false,
    comorbidityWeightCharlson: 0,
  },

  // Diseases of the Genitourinary System (N00 - N99)
  {
    code: 'N17.9',
    shortDesc: 'Acute kidney failure, unspecified',
    longDesc: 'Acute kidney injury (AKI) marked by rapid decline in glomerular filtration rate, rise in serum creatinine, and oliguria.',
    chapter: 'Diseases of the genitourinary system',
    hccV28Category: 'HCC 135 (Acute Renal Failure)',
    snomedCode: '14669001',
    isChronic: false,
    comorbidityWeightCharlson: 0,
  },
  {
    code: 'N18.30',
    shortDesc: 'Chronic kidney disease, stage 3 unspecified',
    longDesc: 'Moderate chronic kidney disease with persistent eGFR between 30 and 59 mL/min/1.73m2 for >= 3 months.',
    chapter: 'Diseases of the genitourinary system',
    hccV28Category: 'HCC 138 (Chronic Kidney Disease, Moderate Stage 3)',
    snomedCode: '433144002',
    isChronic: true,
    comorbidityWeightCharlson: 1,
  },
  {
    code: 'N18.4',
    shortDesc: 'Chronic kidney disease, stage 4 (severe)',
    longDesc: 'Severe chronic kidney disease with persistent eGFR between 15 and 29 mL/min/1.73m2.',
    chapter: 'Diseases of the genitourinary system',
    hccV28Category: 'HCC 137 (Chronic Kidney Disease, Severe Stage 4)',
    snomedCode: '431856006',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
  {
    code: 'N18.6',
    shortDesc: 'End stage renal disease',
    longDesc: 'End-stage renal disease (ESRD / Stage 5 CKD on chronic maintenance hemodialysis or peritoneal dialysis).',
    chapter: 'Diseases of the genitourinary system',
    hccV28Category: 'HCC 136 (Chronic Kidney Disease, Stage 5 or ESRD)',
    snomedCode: '46177005',
    isChronic: true,
    comorbidityWeightCharlson: 2,
  },
];

export const COMPREHENSIVE_CPT_DATABASE: DetailedCptRecord[] = [
  // Evaluation & Management (Outpatient)
  {
    code: '99202',
    shortDesc: 'Office/outpatient visit new patient, 15-29 mins, straightforward MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 2.11,
    workRvu: 0.93,
    practiceExpenseRvu: 1.1,
    malpracticeRvu: 0.08,
    medicareAllowedAmountUsd: 73.85,
    requiresPriorAuth: false,
  },
  {
    code: '99203',
    shortDesc: 'Office/outpatient visit new patient, 30-44 mins, low level MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 3.25,
    workRvu: 1.6,
    practiceExpenseRvu: 1.51,
    malpracticeRvu: 0.14,
    medicareAllowedAmountUsd: 113.75,
    requiresPriorAuth: false,
  },
  {
    code: '99204',
    shortDesc: 'Office/outpatient visit new patient, 45-59 mins, moderate MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 4.86,
    workRvu: 2.6,
    practiceExpenseRvu: 2.05,
    malpracticeRvu: 0.21,
    medicareAllowedAmountUsd: 170.1,
    requiresPriorAuth: false,
  },
  {
    code: '99205',
    shortDesc: 'Office/outpatient visit new patient, 60-74 mins, high MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 6.38,
    workRvu: 3.5,
    practiceExpenseRvu: 2.59,
    malpracticeRvu: 0.29,
    medicareAllowedAmountUsd: 223.3,
    requiresPriorAuth: false,
  },
  {
    code: '99213',
    shortDesc: 'Office/outpatient visit established patient, 20-29 mins, low MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 2.62,
    workRvu: 1.3,
    practiceExpenseRvu: 1.22,
    malpracticeRvu: 0.1,
    medicareAllowedAmountUsd: 91.7,
    requiresPriorAuth: false,
  },
  {
    code: '99214',
    shortDesc: 'Office/outpatient visit established patient, 30-39 mins, moderate MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 3.75,
    workRvu: 1.92,
    practiceExpenseRvu: 1.67,
    malpracticeRvu: 0.16,
    medicareAllowedAmountUsd: 131.25,
    requiresPriorAuth: false,
  },
  {
    code: '99215',
    shortDesc: 'Office/outpatient visit established patient, 40-54 mins, high MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 5.25,
    workRvu: 2.8,
    practiceExpenseRvu: 2.22,
    malpracticeRvu: 0.23,
    medicareAllowedAmountUsd: 183.75,
    requiresPriorAuth: false,
  },

  // Inpatient & Critical Care E&M
  {
    code: '99221',
    shortDesc: 'Initial hospital care, per day, straightforward/low MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 3.12,
    workRvu: 1.63,
    practiceExpenseRvu: 1.35,
    malpracticeRvu: 0.14,
    medicareAllowedAmountUsd: 109.2,
    requiresPriorAuth: false,
  },
  {
    code: '99223',
    shortDesc: 'Initial hospital care, per day, high complexity MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 6.15,
    workRvu: 3.86,
    practiceExpenseRvu: 1.96,
    malpracticeRvu: 0.33,
    medicareAllowedAmountUsd: 215.25,
    requiresPriorAuth: false,
  },
  {
    code: '99232',
    shortDesc: 'Subsequent hospital care, per day, moderate complexity MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 2.34,
    workRvu: 1.39,
    practiceExpenseRvu: 0.84,
    malpracticeRvu: 0.11,
    medicareAllowedAmountUsd: 81.9,
    requiresPriorAuth: false,
  },
  {
    code: '99291',
    shortDesc: 'Critical care, evaluation and management of critically ill, first 30-74 mins',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 7.02,
    workRvu: 4.5,
    practiceExpenseRvu: 2.15,
    malpracticeRvu: 0.37,
    medicareAllowedAmountUsd: 245.7,
    requiresPriorAuth: false,
  },

  // Emergency Department E&M
  {
    code: '99284',
    shortDesc: 'Emergency department visit, high severity, moderate MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 3.82,
    workRvu: 2.56,
    practiceExpenseRvu: 1.05,
    malpracticeRvu: 0.21,
    medicareAllowedAmountUsd: 133.7,
    requiresPriorAuth: false,
  },
  {
    code: '99285',
    shortDesc: 'Emergency department visit, immediate threat to life, high MDM',
    category: 'E&M',
    globalPeriodDays: 0,
    totalRvu: 5.51,
    workRvu: 3.8,
    practiceExpenseRvu: 1.38,
    malpracticeRvu: 0.33,
    medicareAllowedAmountUsd: 192.85,
    requiresPriorAuth: false,
  },

  // Surgical Procedures
  {
    code: '47562',
    shortDesc: 'Laparoscopic cholecystectomy (surgical removal of gallbladder)',
    category: 'SURGERY',
    globalPeriodDays: 90,
    totalRvu: 18.25,
    workRvu: 11.2,
    practiceExpenseRvu: 5.9,
    malpracticeRvu: 1.15,
    medicareAllowedAmountUsd: 638.75,
    requiresPriorAuth: true,
  },
  {
    code: '44970',
    shortDesc: 'Laparoscopic appendectomy',
    category: 'SURGERY',
    globalPeriodDays: 90,
    totalRvu: 15.6,
    workRvu: 9.8,
    practiceExpenseRvu: 4.85,
    malpracticeRvu: 0.95,
    medicareAllowedAmountUsd: 546.0,
    requiresPriorAuth: false,
  },
  {
    code: '33533',
    shortDesc: 'Coronary artery bypass graft (CABG), single arterial graft',
    category: 'SURGERY',
    globalPeriodDays: 90,
    totalRvu: 52.4,
    workRvu: 32.5,
    practiceExpenseRvu: 16.2,
    malpracticeRvu: 3.7,
    medicareAllowedAmountUsd: 1834.0,
    requiresPriorAuth: true,
  },
  {
    code: '27447',
    shortDesc: 'Total knee arthroplasty (TKA)',
    category: 'SURGERY',
    globalPeriodDays: 90,
    totalRvu: 38.5,
    workRvu: 21.0,
    practiceExpenseRvu: 14.8,
    malpracticeRvu: 2.7,
    medicareAllowedAmountUsd: 1347.5,
    requiresPriorAuth: true,
  },

  // Radiology & Imaging
  {
    code: '71275',
    shortDesc: 'Computed tomographic angiography, chest (CTA PE protocol) with contrast',
    category: 'RADIOLOGY',
    globalPeriodDays: 'XXX',
    totalRvu: 8.95,
    workRvu: 2.3,
    practiceExpenseRvu: 6.45,
    malpracticeRvu: 0.2,
    medicareAllowedAmountUsd: 313.25,
    requiresPriorAuth: true,
  },
  {
    code: '70553',
    shortDesc: 'Magnetic resonance imaging (MRI) brain with and without IV contrast',
    category: 'RADIOLOGY',
    globalPeriodDays: 'XXX',
    totalRvu: 11.2,
    workRvu: 2.9,
    practiceExpenseRvu: 8.05,
    malpracticeRvu: 0.25,
    medicareAllowedAmountUsd: 392.0,
    requiresPriorAuth: true,
  },
  {
    code: '71046',
    shortDesc: 'Radiologic examination, chest; 2 views (PA and lateral)',
    category: 'RADIOLOGY',
    globalPeriodDays: 'XXX',
    totalRvu: 0.95,
    workRvu: 0.5,
    practiceExpenseRvu: 0.41,
    malpracticeRvu: 0.04,
    medicareAllowedAmountUsd: 33.25,
    requiresPriorAuth: false,
  },
];
