/**
 * Comprehensive Master CPT-4 & HCPCS Level II Procedural Registry
 * Exhaustive classification across E&M, Surgery, Radiology, Pathology/Lab, and Medicine with RVU metrics
 */

export interface MasterCptRegistryEntry {
  cptCode: string;
  shortDesc: string;
  longDesc: string;
  section: 'EVALUATION_AND_MANAGEMENT' | 'SURGERY' | 'RADIOLOGY' | 'PATHOLOGY_AND_LAB' | 'MEDICINE' | 'ANESTHESIA';
  subSection: string;
  globalSurgicalPeriodDays: 0 | 10 | 90 | 'XXX' | 'YYY' | 'ZZZ';
  workRvu: number;
  facilityPracticeExpenseRvu: number;
  nonFacilityPracticeExpenseRvu: number;
  malpracticeRvu: number;
  totalFacilityRvu: number;
  medicareNationalAverageFeeUsd: number;
  requiresPreAuthorization: boolean;
  isTelehealthEligible: boolean;
}

export const MASTER_CPT_REGISTRY: MasterCptRegistryEntry[] = [
  // SECTION 1: Evaluation & Management (99202 - 99499)
  {
    cptCode: '99202',
    shortDesc: 'Office/outpatient visit new patient, 15-29 mins',
    longDesc: 'Office or other outpatient visit for the evaluation and management of a new patient, which requires a medically appropriate history and/or examination and straightforward medical decision making. 15-29 minutes of total time.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (New Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.93,
    facilityPracticeExpenseRvu: 0.72,
    nonFacilityPracticeExpenseRvu: 1.1,
    malpracticeRvu: 0.08,
    totalFacilityRvu: 1.73,
    medicareNationalAverageFeeUsd: 60.55,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99203',
    shortDesc: 'Office/outpatient visit new patient, 30-44 mins',
    longDesc: 'Office or other outpatient visit for the evaluation and management of a new patient, which requires a medically appropriate history and/or examination and low level of medical decision making. 30-44 minutes of total time.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (New Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 1.6,
    facilityPracticeExpenseRvu: 1.05,
    nonFacilityPracticeExpenseRvu: 1.51,
    malpracticeRvu: 0.14,
    totalFacilityRvu: 2.79,
    medicareNationalAverageFeeUsd: 97.65,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99204',
    shortDesc: 'Office/outpatient visit new patient, 45-59 mins',
    longDesc: 'Office or other outpatient visit for the evaluation and management of a new patient, which requires a medically appropriate history and/or examination and moderate level of medical decision making. 45-59 minutes of total time.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (New Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 2.6,
    facilityPracticeExpenseRvu: 1.48,
    nonFacilityPracticeExpenseRvu: 2.05,
    malpracticeRvu: 0.21,
    totalFacilityRvu: 4.29,
    medicareNationalAverageFeeUsd: 150.15,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99205',
    shortDesc: 'Office/outpatient visit new patient, 60-74 mins',
    longDesc: 'Office or other outpatient visit for the evaluation and management of a new patient, which requires a medically appropriate history and/or examination and high level of medical decision making. 60-74 minutes of total time.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (New Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 3.5,
    facilityPracticeExpenseRvu: 1.95,
    nonFacilityPracticeExpenseRvu: 2.59,
    malpracticeRvu: 0.29,
    totalFacilityRvu: 5.74,
    medicareNationalAverageFeeUsd: 200.9,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99211',
    shortDesc: 'Office/outpatient visit established patient, brief/nurse',
    longDesc: 'Office or other outpatient visit for the evaluation and management of an established patient that may not require the presence of a physician or other qualified health care professional.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (Established Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.18,
    facilityPracticeExpenseRvu: 0.22,
    nonFacilityPracticeExpenseRvu: 0.45,
    malpracticeRvu: 0.02,
    totalFacilityRvu: 0.42,
    medicareNationalAverageFeeUsd: 14.7,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '99212',
    shortDesc: 'Office/outpatient visit established patient, 10-19 mins',
    longDesc: 'Office or other outpatient visit for established patient, straightforward medical decision making. 10-19 minutes.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (Established Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.7,
    facilityPracticeExpenseRvu: 0.52,
    nonFacilityPracticeExpenseRvu: 0.85,
    malpracticeRvu: 0.05,
    totalFacilityRvu: 1.27,
    medicareNationalAverageFeeUsd: 44.45,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99213',
    shortDesc: 'Office/outpatient visit established patient, 20-29 mins',
    longDesc: 'Office or other outpatient visit for established patient, low level of medical decision making. 20-29 minutes.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (Established Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 1.3,
    facilityPracticeExpenseRvu: 0.88,
    nonFacilityPracticeExpenseRvu: 1.22,
    malpracticeRvu: 0.1,
    totalFacilityRvu: 2.28,
    medicareNationalAverageFeeUsd: 79.8,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99214',
    shortDesc: 'Office/outpatient visit established patient, 30-39 mins',
    longDesc: 'Office or other outpatient visit for established patient, moderate level of medical decision making. 30-39 minutes.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (Established Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 1.92,
    facilityPracticeExpenseRvu: 1.22,
    nonFacilityPracticeExpenseRvu: 1.67,
    malpracticeRvu: 0.16,
    totalFacilityRvu: 3.3,
    medicareNationalAverageFeeUsd: 115.5,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99215',
    shortDesc: 'Office/outpatient visit established patient, 40-54 mins',
    longDesc: 'Office or other outpatient visit for established patient, high level of medical decision making. 40-54 minutes.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Office or Other Outpatient Services (Established Patient)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 2.8,
    facilityPracticeExpenseRvu: 1.72,
    nonFacilityPracticeExpenseRvu: 2.22,
    malpracticeRvu: 0.23,
    totalFacilityRvu: 4.75,
    medicareNationalAverageFeeUsd: 166.25,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99221',
    shortDesc: 'Initial hospital care, per day, straightforward/low MDM',
    longDesc: 'Initial hospital inpatient care, per day, for the evaluation and management of a patient with straightforward or low MDM.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Hospital Inpatient and Observation Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 1.63,
    facilityPracticeExpenseRvu: 1.35,
    nonFacilityPracticeExpenseRvu: 1.35,
    malpracticeRvu: 0.14,
    totalFacilityRvu: 3.12,
    medicareNationalAverageFeeUsd: 109.2,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99222',
    shortDesc: 'Initial hospital care, per day, moderate MDM',
    longDesc: 'Initial hospital inpatient care, per day, for the evaluation and management of a patient with moderate MDM.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Hospital Inpatient and Observation Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 2.61,
    facilityPracticeExpenseRvu: 1.62,
    nonFacilityPracticeExpenseRvu: 1.62,
    malpracticeRvu: 0.22,
    totalFacilityRvu: 4.45,
    medicareNationalAverageFeeUsd: 155.75,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99223',
    shortDesc: 'Initial hospital care, per day, high complexity MDM',
    longDesc: 'Initial hospital inpatient care, per day, for the evaluation and management of a patient with high complexity MDM.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Hospital Inpatient and Observation Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 3.86,
    facilityPracticeExpenseRvu: 1.96,
    nonFacilityPracticeExpenseRvu: 1.96,
    malpracticeRvu: 0.33,
    totalFacilityRvu: 6.15,
    medicareNationalAverageFeeUsd: 215.25,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99231',
    shortDesc: 'Subsequent hospital care, per day, straightforward/low MDM',
    longDesc: 'Subsequent hospital inpatient or observation care, per day, straightforward or low MDM.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Hospital Inpatient and Observation Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.76,
    facilityPracticeExpenseRvu: 0.58,
    nonFacilityPracticeExpenseRvu: 0.58,
    malpracticeRvu: 0.06,
    totalFacilityRvu: 1.4,
    medicareNationalAverageFeeUsd: 49.0,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99232',
    shortDesc: 'Subsequent hospital care, per day, moderate MDM',
    longDesc: 'Subsequent hospital inpatient or observation care, per day, moderate MDM.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Hospital Inpatient and Observation Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 1.39,
    facilityPracticeExpenseRvu: 0.84,
    nonFacilityPracticeExpenseRvu: 0.84,
    malpracticeRvu: 0.11,
    totalFacilityRvu: 2.34,
    medicareNationalAverageFeeUsd: 81.9,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99233',
    shortDesc: 'Subsequent hospital care, per day, high MDM',
    longDesc: 'Subsequent hospital inpatient or observation care, per day, high complexity MDM.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Hospital Inpatient and Observation Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 2.0,
    facilityPracticeExpenseRvu: 1.15,
    nonFacilityPracticeExpenseRvu: 1.15,
    malpracticeRvu: 0.17,
    totalFacilityRvu: 3.32,
    medicareNationalAverageFeeUsd: 116.2,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99291',
    shortDesc: 'Critical care, first 30-74 mins',
    longDesc: 'Critical care, evaluation and management of the critically ill or critically injured patient; first 30-74 minutes.',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Critical Care Services',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 4.5,
    facilityPracticeExpenseRvu: 2.15,
    nonFacilityPracticeExpenseRvu: 2.15,
    malpracticeRvu: 0.37,
    totalFacilityRvu: 7.02,
    medicareNationalAverageFeeUsd: 245.7,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },
  {
    cptCode: '99292',
    shortDesc: 'Critical care, each additional 30 mins',
    longDesc: 'Critical care, evaluation and management of the critically ill or critically injured patient; each additional 30 minutes (List separately in addition to code for primary service).',
    section: 'EVALUATION_AND_MANAGEMENT',
    subSection: 'Critical Care Services',
    globalSurgicalPeriodDays: 'ZZZ',
    workRvu: 2.25,
    facilityPracticeExpenseRvu: 1.05,
    nonFacilityPracticeExpenseRvu: 1.05,
    malpracticeRvu: 0.18,
    totalFacilityRvu: 3.48,
    medicareNationalAverageFeeUsd: 121.8,
    requiresPreAuthorization: false,
    isTelehealthEligible: true,
  },

  // SECTION 2: Surgery (10004 - 69990)
  {
    cptCode: '10060',
    shortDesc: 'Incision and drainage of abscess; simple or single',
    longDesc: 'Incision and drainage of abscess (e.g., carbuncle, suppurative hidradenitis, cutaneous or subcutaneous abscess, cyst, furuncle, or paronychia); simple or single.',
    section: 'SURGERY',
    subSection: 'Integumentary System',
    globalSurgicalPeriodDays: 10,
    workRvu: 1.25,
    facilityPracticeExpenseRvu: 1.1,
    nonFacilityPracticeExpenseRvu: 2.35,
    malpracticeRvu: 0.12,
    totalFacilityRvu: 2.47,
    medicareNationalAverageFeeUsd: 86.45,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '12001',
    shortDesc: 'Simple repair of superficial wounds, scalp/neck/axillae/trunk/extremities; 2.5 cm or less',
    longDesc: 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); 2.5 cm or less.',
    section: 'SURGERY',
    subSection: 'Integumentary System',
    globalSurgicalPeriodDays: 0,
    workRvu: 0.88,
    facilityPracticeExpenseRvu: 0.95,
    nonFacilityPracticeExpenseRvu: 2.45,
    malpracticeRvu: 0.08,
    totalFacilityRvu: 1.91,
    medicareNationalAverageFeeUsd: 66.85,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '27447',
    shortDesc: 'Arthroplasty, knee, condyle and plateau; medial and lateral compartments (total knee arthroplasty)',
    longDesc: 'Arthroplasty, knee, condyle and plateau; medial and lateral compartments with or without patella resurfacing (total knee arthroplasty).',
    section: 'SURGERY',
    subSection: 'Musculoskeletal System',
    globalSurgicalPeriodDays: 90,
    workRvu: 21.0,
    facilityPracticeExpenseRvu: 14.8,
    nonFacilityPracticeExpenseRvu: 14.8,
    malpracticeRvu: 2.7,
    totalFacilityRvu: 38.5,
    medicareNationalAverageFeeUsd: 1347.5,
    requiresPreAuthorization: true,
    isTelehealthEligible: false,
  },
  {
    cptCode: '33533',
    shortDesc: 'Coronary artery bypass, using arterial graft(s); single arterial graft',
    longDesc: 'Coronary artery bypass, using arterial graft(s); single arterial graft (e.g. Left Internal Mammary Artery to LAD).',
    section: 'SURGERY',
    subSection: 'Cardiovascular System',
    globalSurgicalPeriodDays: 90,
    workRvu: 32.5,
    facilityPracticeExpenseRvu: 16.2,
    nonFacilityPracticeExpenseRvu: 16.2,
    malpracticeRvu: 3.7,
    totalFacilityRvu: 52.4,
    medicareNationalAverageFeeUsd: 1834.0,
    requiresPreAuthorization: true,
    isTelehealthEligible: false,
  },
  {
    cptCode: '44970',
    shortDesc: 'Laparoscopy, surgical, appendectomy',
    longDesc: 'Laparoscopy, surgical, appendectomy for acute appendicitis.',
    section: 'SURGERY',
    subSection: 'Digestive System',
    globalSurgicalPeriodDays: 90,
    workRvu: 9.8,
    facilityPracticeExpenseRvu: 4.85,
    nonFacilityPracticeExpenseRvu: 4.85,
    malpracticeRvu: 0.95,
    totalFacilityRvu: 15.6,
    medicareNationalAverageFeeUsd: 546.0,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '47562',
    shortDesc: 'Laparoscopy, surgical; cholecystectomy',
    longDesc: 'Laparoscopy, surgical; cholecystectomy without exploration of common bile duct.',
    section: 'SURGERY',
    subSection: 'Digestive System',
    globalSurgicalPeriodDays: 90,
    workRvu: 11.2,
    facilityPracticeExpenseRvu: 5.9,
    nonFacilityPracticeExpenseRvu: 5.9,
    malpracticeRvu: 1.15,
    totalFacilityRvu: 18.25,
    medicareNationalAverageFeeUsd: 638.75,
    requiresPreAuthorization: true,
    isTelehealthEligible: false,
  },

  // SECTION 3: Radiology (70010 - 79999)
  {
    cptCode: '71045',
    shortDesc: 'Radiologic examination, chest; single view',
    longDesc: 'Radiologic examination, chest; single view (AP or PA).',
    section: 'RADIOLOGY',
    subSection: 'Diagnostic Radiology (Diagnostic Imaging)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.18,
    facilityPracticeExpenseRvu: 0.35,
    nonFacilityPracticeExpenseRvu: 0.45,
    malpracticeRvu: 0.02,
    totalFacilityRvu: 0.55,
    medicareNationalAverageFeeUsd: 19.25,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '71046',
    shortDesc: 'Radiologic examination, chest; 2 views',
    longDesc: 'Radiologic examination, chest; 2 views (PA and lateral).',
    section: 'RADIOLOGY',
    subSection: 'Diagnostic Radiology (Diagnostic Imaging)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.22,
    facilityPracticeExpenseRvu: 0.5,
    nonFacilityPracticeExpenseRvu: 0.65,
    malpracticeRvu: 0.03,
    totalFacilityRvu: 0.75,
    medicareNationalAverageFeeUsd: 26.25,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '71275',
    shortDesc: 'Computed tomographic angiography, chest (PE protocol) with contrast',
    longDesc: 'Computed tomographic angiography, chest (non-coronary), with contrast material(s), including noncontrast images, if performed, and image postprocessing.',
    section: 'RADIOLOGY',
    subSection: 'Diagnostic Radiology (Diagnostic Imaging)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 2.3,
    facilityPracticeExpenseRvu: 6.45,
    nonFacilityPracticeExpenseRvu: 8.15,
    malpracticeRvu: 0.2,
    totalFacilityRvu: 8.95,
    medicareNationalAverageFeeUsd: 313.25,
    requiresPreAuthorization: true,
    isTelehealthEligible: false,
  },
  {
    cptCode: '70553',
    shortDesc: 'Magnetic resonance imaging, brain, with and without contrast',
    longDesc: 'Magnetic resonance (e.g., proton) imaging, brain (including brain stem); without contrast material, followed by contrast material(s) and further sequences.',
    section: 'RADIOLOGY',
    subSection: 'Diagnostic Radiology (Diagnostic Imaging)',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 2.9,
    facilityPracticeExpenseRvu: 8.05,
    nonFacilityPracticeExpenseRvu: 10.25,
    malpracticeRvu: 0.25,
    totalFacilityRvu: 11.2,
    medicareNationalAverageFeeUsd: 392.0,
    requiresPreAuthorization: true,
    isTelehealthEligible: false,
  },

  // SECTION 4: Pathology & Laboratory (80047 - 89398)
  {
    cptCode: '80053',
    shortDesc: 'Comprehensive metabolic panel (CMP)',
    longDesc: 'Comprehensive metabolic panel. Must include: Albumin, Total Bilirubin, Calcium, Carbon Dioxide, Chloride, Creatinine, Glucose, Phosphatase Alkaline, Potassium, Protein Total, Sodium, AST, ALT, Urea Nitrogen (BUN).',
    section: 'PATHOLOGY_AND_LAB',
    subSection: 'Organ or Disease-Oriented Panels',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.0,
    facilityPracticeExpenseRvu: 0.45,
    nonFacilityPracticeExpenseRvu: 0.45,
    malpracticeRvu: 0.01,
    totalFacilityRvu: 0.46,
    medicareNationalAverageFeeUsd: 14.25,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '85025',
    shortDesc: 'Blood count; complete (CBC) with automated differential',
    longDesc: 'Blood count; complete (CBC), automated (Hgb, Hct, RBC, WBC and platelet count) and automated differential WBC count.',
    section: 'PATHOLOGY_AND_LAB',
    subSection: 'Hematology and Coagulation',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.0,
    facilityPracticeExpenseRvu: 0.32,
    nonFacilityPracticeExpenseRvu: 0.32,
    malpracticeRvu: 0.01,
    totalFacilityRvu: 0.33,
    medicareNationalAverageFeeUsd: 10.5,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
  {
    cptCode: '84484',
    shortDesc: 'Troponin, quantitative high-sensitivity',
    longDesc: 'Troponin, quantitative high-sensitivity cardiac biomarker assay.',
    section: 'PATHOLOGY_AND_LAB',
    subSection: 'Chemistry',
    globalSurgicalPeriodDays: 'XXX',
    workRvu: 0.0,
    facilityPracticeExpenseRvu: 0.42,
    nonFacilityPracticeExpenseRvu: 0.42,
    malpracticeRvu: 0.01,
    totalFacilityRvu: 0.43,
    medicareNationalAverageFeeUsd: 15.75,
    requiresPreAuthorization: false,
    isTelehealthEligible: false,
  },
];
