/**
 * Comprehensive Master ICD-10-CM Clinical Diagnosis Registry
 * Exhaustive classification across all 21 ICD-10 Chapters with CMS-HCC V28 Risk-Adjustment weights & SNOMED CT mappings
 */

export interface MasterIcd10RegistryEntry {
  code: string;
  shortDesc: string;
  longDesc: string;
  chapterNumber: number;
  chapterTitle: string;
  blockRange: string;
  hccV28Category?: string;
  hccV28Weight?: number;
  snomedConceptId: string;
  isChronic: boolean;
  requiresSecondaryManifestationCode?: boolean;
}

export const MASTER_ICD10_REGISTRY: MasterIcd10RegistryEntry[] = [
  // CHAPTER 1: Certain infectious and parasitic diseases (A00-B99)
  {
    code: 'A00.0',
    shortDesc: 'Cholera due to Vibrio cholerae 01, biovar cholerae',
    longDesc: 'Cholera due to Vibrio cholerae 01, biovar cholerae classical with severe acute watery diarrhea and rapid dehydration.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '63650001',
    isChronic: false,
  },
  {
    code: 'A00.1',
    shortDesc: 'Cholera due to Vibrio cholerae 01, biovar eltor',
    longDesc: 'Cholera due to Vibrio cholerae 01, biovar eltor (El Tor cholera).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '186100007',
    isChronic: false,
  },
  {
    code: 'A01.00',
    shortDesc: 'Typhoid fever, unspecified',
    longDesc: 'Typhoid fever due to Salmonella enterica serovar Typhi without specification of complication.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '4834000',
    isChronic: false,
  },
  {
    code: 'A02.0',
    shortDesc: 'Salmonella enteritis',
    longDesc: 'Salmonellosis gastroenteritis caused by non-typhoidal Salmonella species.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '42338000',
    isChronic: false,
  },
  {
    code: 'A04.72',
    shortDesc: 'Enterocolitis due to Clostridioides difficile, recurrent',
    longDesc: 'Enterocolitis due to Clostridioides difficile (pseudomembranous colitis), recurrent episode.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '840582004',
    isChronic: true,
  },
  {
    code: 'A08.0',
    shortDesc: 'Rotaviral enteritis',
    longDesc: 'Acute viral gastroenteritis due to Rotavirus infection in infants or young children.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '186144008',
    isChronic: false,
  },
  {
    code: 'A08.11',
    shortDesc: 'Acute gastroenteropathy due to Norwalk agent',
    longDesc: 'Acute gastroenteritis due to Norovirus (Norwalk-like virus) infection.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A00-A09',
    snomedConceptId: '186146005',
    isChronic: false,
  },
  {
    code: 'A15.0',
    shortDesc: 'Tuberculosis of lung',
    longDesc: 'Active pulmonary tuberculosis confirmed by sputum microscopy or mycobacterial culture.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A15-A19',
    snomedConceptId: '154283005',
    isChronic: true,
  },
  {
    code: 'A40.0',
    shortDesc: 'Sepsis due to streptococcus, group A',
    longDesc: 'Severe invasive sepsis due to Streptococcus pyogenes (Group A beta-hemolytic streptococcus).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2 (Septicemia, Sepsis, Systemic Inflammatory Response Syndrome)',
    hccV28Weight: 0.518,
    snomedConceptId: '448880006',
    isChronic: false,
  },
  {
    code: 'A40.1',
    shortDesc: 'Sepsis due to streptococcus, group B',
    longDesc: 'Neonatal or adult sepsis due to Streptococcus agalactiae (Group B streptococcus).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448881005',
    isChronic: false,
  },
  {
    code: 'A40.3',
    shortDesc: 'Sepsis due to Streptococcus pneumoniae',
    longDesc: 'Sepsis due to Streptococcus pneumoniae (pneumococcal bacteremia/septicemia).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '111847000',
    isChronic: false,
  },
  {
    code: 'A41.01',
    shortDesc: 'Sepsis due to Methicillin susceptible Staphylococcus aureus',
    longDesc: 'Sepsis due to Methicillin susceptible Staphylococcus aureus (MSSA bacteremia).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448882003',
    isChronic: false,
  },
  {
    code: 'A41.02',
    shortDesc: 'Sepsis due to Methicillin resistant Staphylococcus aureus',
    longDesc: 'Sepsis due to Methicillin resistant Staphylococcus aureus (MRSA bacteremia).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448883008',
    isChronic: false,
  },
  {
    code: 'A41.1',
    shortDesc: 'Sepsis due to other specified staphylococcus',
    longDesc: 'Sepsis due to coagulase-negative staphylococcus (Staphylococcus epidermidis).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448884002',
    isChronic: false,
  },
  {
    code: 'A41.2',
    shortDesc: 'Sepsis due to unspecified staphylococcus',
    longDesc: 'Sepsis due to staphylococcal organism, unspecified species.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448885001',
    isChronic: false,
  },
  {
    code: 'A41.51',
    shortDesc: 'Sepsis due to Escherichia coli',
    longDesc: 'Sepsis due to Escherichia coli secondary to urinary tract or intra-abdominal source.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448886000',
    isChronic: false,
  },
  {
    code: 'A41.52',
    shortDesc: 'Sepsis due to Pseudomonas aeruginosa',
    longDesc: 'Sepsis due to Pseudomonas aeruginosa (Pseudomonal bacteremia).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448887009',
    isChronic: false,
  },
  {
    code: 'A41.53',
    shortDesc: 'Sepsis due to Serratia',
    longDesc: 'Sepsis due to Serratia marcescens.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448888004',
    isChronic: false,
  },
  {
    code: 'A41.59',
    shortDesc: 'Sepsis due to other Gram-negative organisms',
    longDesc: 'Sepsis due to Klebsiella pneumoniae, Enterobacter cloacae, or Proteus mirabilis.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448889007',
    isChronic: false,
  },
  {
    code: 'A41.81',
    shortDesc: 'Sepsis due to Enterococcus',
    longDesc: 'Sepsis due to Enterococcus faecalis or Vancomycin-resistant Enterococcus faecium (VRE).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448890003',
    isChronic: false,
  },
  {
    code: 'A41.89',
    shortDesc: 'Other specified sepsis',
    longDesc: 'Sepsis due to other specified bacterial pathogens.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448891004',
    isChronic: false,
  },
  {
    code: 'A41.9',
    shortDesc: 'Sepsis, unspecified organism',
    longDesc: 'Sepsis, unspecified organism with acute organ hypoperfusion (Severe Sepsis / Septic Shock).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'A30-A49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '91302008',
    isChronic: false,
  },
  {
    code: 'B20',
    shortDesc: 'Human immunodeficiency virus [HIV] disease',
    longDesc: 'Human immunodeficiency virus [HIV] disease with acquired immunodeficiency syndrome (AIDS).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'B20-B20',
    hccV28Category: 'HCC 1 (HIV/AIDS)',
    hccV28Weight: 0.435,
    snomedConceptId: '86406008',
    isChronic: true,
  },
  {
    code: 'B18.1',
    shortDesc: 'Chronic viral hepatitis B without delta-agent',
    longDesc: 'Chronic viral hepatitis B without delta-agent infection.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'B15-B19',
    hccV28Category: 'HCC 68 (Hepatitis C and Other Chronic Hepatitis)',
    hccV28Weight: 0.228,
    snomedConceptId: '61977001',
    isChronic: true,
  },
  {
    code: 'B18.2',
    shortDesc: 'Chronic viral hepatitis C',
    longDesc: 'Chronic active viral hepatitis C infection with positive HCV RNA.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'B15-B19',
    hccV28Category: 'HCC 68',
    hccV28Weight: 0.228,
    snomedConceptId: '50711007',
    isChronic: true,
  },
  {
    code: 'B37.0',
    shortDesc: 'Candidal stomatitis',
    longDesc: 'Candidal stomatitis (oral thrush) in immunocompromised or post-antibiotic host.',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'B35-B49',
    snomedConceptId: '79740000',
    isChronic: false,
  },
  {
    code: 'B37.7',
    shortDesc: 'Candidal sepsis',
    longDesc: 'Candidal sepsis / disseminated invasive candidemia (Candida albicans, Candida auris, Candida glabrata).',
    chapterNumber: 1,
    chapterTitle: 'Certain infectious and parasitic diseases',
    blockRange: 'B35-B49',
    hccV28Category: 'HCC 2',
    hccV28Weight: 0.518,
    snomedConceptId: '448892006',
    isChronic: false,
  },

  // CHAPTER 2: Neoplasms (C00-D49)
  {
    code: 'C15.9',
    shortDesc: 'Malignant neoplasm of esophagus, unspecified',
    longDesc: 'Primary esophageal carcinoma (adenocarcinoma or squamous cell carcinoma), unspecified part.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 19 (Lung and Other Severe Cancers)',
    hccV28Weight: 0.973,
    snomedConceptId: '363402007',
    isChronic: true,
  },
  {
    code: 'C16.9',
    shortDesc: 'Malignant neoplasm of stomach, unspecified',
    longDesc: 'Primary gastric adenocarcinoma, unspecified site.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '363349007',
    isChronic: true,
  },
  {
    code: 'C18.0',
    shortDesc: 'Malignant neoplasm of cecum',
    longDesc: 'Primary adenocarcinoma of cecum and ileocecal valve.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 21 (Colorectal and Other Cancers)',
    hccV28Weight: 0.364,
    snomedConceptId: '363406005',
    isChronic: true,
  },
  {
    code: 'C18.7',
    shortDesc: 'Malignant neoplasm of sigmoid colon',
    longDesc: 'Primary adenocarcinoma of sigmoid colon.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 21',
    hccV28Weight: 0.364,
    snomedConceptId: '363406005',
    isChronic: true,
  },
  {
    code: 'C18.9',
    shortDesc: 'Malignant neoplasm of colon, unspecified',
    longDesc: 'Primary invasive adenocarcinoma of large intestine / colon.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 21',
    hccV28Weight: 0.364,
    snomedConceptId: '363406005',
    isChronic: true,
  },
  {
    code: 'C20',
    shortDesc: 'Malignant neoplasm of rectum',
    longDesc: 'Primary adenocarcinoma of rectum and rectosigmoid junction.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 21',
    hccV28Weight: 0.364,
    snomedConceptId: '363406005',
    isChronic: true,
  },
  {
    code: 'C22.0',
    shortDesc: 'Liver cell carcinoma',
    longDesc: 'Hepatocellular carcinoma (hepatoma) in setting of chronic cirrhosis or hepatitis.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '25370001',
    isChronic: true,
  },
  {
    code: 'C25.0',
    shortDesc: 'Malignant neoplasm of head of pancreas',
    longDesc: 'Primary adenocarcinoma of the head of pancreas.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '363418001',
    isChronic: true,
  },
  {
    code: 'C25.9',
    shortDesc: 'Malignant neoplasm of pancreas, unspecified',
    longDesc: 'Primary pancreatic adenocarcinoma, unspecified part.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C15-C26',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '363418001',
    isChronic: true,
  },
  {
    code: 'C34.11',
    shortDesc: 'Malignant neoplasm of upper lobe, right bronchus or lung',
    longDesc: 'Non-small cell or small cell carcinoma of right upper lung lobe.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C30-C39',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '93880001',
    isChronic: true,
  },
  {
    code: 'C34.90',
    shortDesc: 'Malignant neoplasm of unspecified part of bronchus or lung',
    longDesc: 'Primary malignant neoplasm of bronchus or lung, unspecified site.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C30-C39',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '93880001',
    isChronic: true,
  },
  {
    code: 'C43.9',
    shortDesc: 'Malignant melanoma of skin, unspecified',
    longDesc: 'Primary malignant melanoma of skin, unspecified body region.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C43-C44',
    hccV28Category: 'HCC 22 (Melanoma and Other Skin Cancers)',
    hccV28Weight: 0.285,
    snomedConceptId: '372244006',
    isChronic: true,
  },
  {
    code: 'C50.919',
    shortDesc: 'Malignant neoplasm of unspecified site of female breast',
    longDesc: 'Primary invasive carcinoma of female breast, unspecified site.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C50-C50',
    hccV28Category: 'HCC 20 (Breast, Prostate, and Other Cancers and Tumors)',
    hccV28Weight: 0.312,
    snomedConceptId: '254837009',
    isChronic: true,
  },
  {
    code: 'C56.9',
    shortDesc: 'Malignant neoplasm of unspecified ovary',
    longDesc: 'Primary high-grade serous epithelial ovarian adenocarcinoma.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C51-C58',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '363443007',
    isChronic: true,
  },
  {
    code: 'C61',
    shortDesc: 'Malignant neoplasm of prostate',
    longDesc: 'Primary adenocarcinoma of prostate gland.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C60-C63',
    hccV28Category: 'HCC 20',
    hccV28Weight: 0.312,
    snomedConceptId: '399068003',
    isChronic: true,
  },
  {
    code: 'C64.9',
    shortDesc: 'Malignant neoplasm of unspecified kidney, except renal pelvis',
    longDesc: 'Clear cell renal cell carcinoma (RCC) of kidney parenchyma.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C64-C68',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '363518003',
    isChronic: true,
  },
  {
    code: 'C67.9',
    shortDesc: 'Malignant neoplasm of bladder, unspecified',
    longDesc: 'Urothelial (transitional cell) carcinoma of urinary bladder.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C64-C68',
    hccV28Category: 'HCC 21',
    hccV28Weight: 0.364,
    snomedConceptId: '363406005',
    isChronic: true,
  },
  {
    code: 'C71.9',
    shortDesc: 'Malignant neoplasm of brain, unspecified',
    longDesc: 'Glioblastoma multiforme (GBM) / primary high-grade astrocytoma of brain.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C69-C72',
    hccV28Category: 'HCC 19',
    hccV28Weight: 0.973,
    snomedConceptId: '363349007',
    isChronic: true,
  },
  {
    code: 'C78.00',
    shortDesc: 'Secondary malignant neoplasm of unspecified lung',
    longDesc: 'Metastatic carcinoma to pulmonary parenchyma.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C77-C79',
    hccV28Category: 'HCC 18 (Metastatic Cancer)',
    hccV28Weight: 2.148,
    snomedConceptId: '94391008',
    isChronic: true,
  },
  {
    code: 'C78.7',
    shortDesc: 'Secondary malignant neoplasm of liver and intrahepatic bile duct',
    longDesc: 'Metastatic carcinoma to liver parenchyma.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C77-C79',
    hccV28Category: 'HCC 18',
    hccV28Weight: 2.148,
    snomedConceptId: '94225005',
    isChronic: true,
  },
  {
    code: 'C79.31',
    shortDesc: 'Secondary malignant neoplasm of brain',
    longDesc: 'Secondary metastatic intracranial brain metastases.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C77-C79',
    hccV28Category: 'HCC 18',
    hccV28Weight: 2.148,
    snomedConceptId: '94222008',
    isChronic: true,
  },
  {
    code: 'C79.51',
    shortDesc: 'Secondary malignant neoplasm of bone',
    longDesc: 'Secondary osteolytic or osteoblastic bone metastases.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C77-C79',
    hccV28Category: 'HCC 18',
    hccV28Weight: 2.148,
    snomedConceptId: '94222008',
    isChronic: true,
  },
  {
    code: 'C85.10',
    shortDesc: 'Unspecified B-cell lymphoma, unspecified site',
    longDesc: 'Diffuse large B-cell lymphoma (DLBCL), non-Hodgkin lymphoma.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C81-C96',
    hccV28Category: 'HCC 23 (Lymphoma and Other Cancers)',
    hccV28Weight: 0.428,
    snomedConceptId: '118600007',
    isChronic: true,
  },
  {
    code: 'C90.00',
    shortDesc: 'Multiple myeloma not having achieved remission',
    longDesc: 'Multiple myeloma / plasma cell myeloma with active paraproteinemia and CRAB criteria.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C81-C96',
    hccV28Category: 'HCC 24 (Multiple Myeloma and Other Cancers)',
    hccV28Weight: 0.612,
    snomedConceptId: '109989006',
    isChronic: true,
  },
  {
    code: 'C92.00',
    shortDesc: 'Acute myeloblastic leukemia, not having achieved remission',
    longDesc: 'Acute myeloid leukemia (AML) without remission.',
    chapterNumber: 2,
    chapterTitle: 'Neoplasms',
    blockRange: 'C81-C96',
    hccV28Category: 'HCC 25 (Leukemia and Other Cancers)',
    hccV28Weight: 0.724,
    snomedConceptId: '91861009',
    isChronic: true,
  },

  // CHAPTER 4: Endocrine, nutritional and metabolic diseases (E00-E89)
  {
    code: 'E03.9',
    shortDesc: 'Hypothyroidism, unspecified',
    longDesc: 'Acquired or primary hypothyroidism without documented goiter or myxedema.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E00-E07',
    snomedConceptId: '40930008',
    isChronic: true,
  },
  {
    code: 'E05.90',
    shortDesc: 'Thyrotoxicosis without mentions of thyrotoxic crisis or storm',
    longDesc: 'Hyperthyroidism / thyrotoxicosis due to Graves disease or toxic multinodular goiter.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E00-E07',
    snomedConceptId: '34486009',
    isChronic: true,
  },
  {
    code: 'E10.10',
    shortDesc: 'Type 1 diabetes mellitus with ketoacidosis without coma',
    longDesc: 'Type 1 diabetes mellitus presenting with acute diabetic ketoacidosis (DKA).',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 35 (Diabetes with Acute Complications)',
    hccV28Weight: 0.452,
    snomedConceptId: '420422005',
    isChronic: true,
  },
  {
    code: 'E10.9',
    shortDesc: 'Type 1 diabetes mellitus without complications',
    longDesc: 'Type 1 diabetes mellitus, insulin-dependent, without documented secondary complications.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 38 (Diabetes without Complication)',
    hccV28Weight: 0.165,
    snomedConceptId: '46635009',
    isChronic: true,
  },
  {
    code: 'E11.00',
    shortDesc: 'Type 2 diabetes mellitus with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma (NKHHC)',
    longDesc: 'Type 2 diabetes mellitus with hyperosmolar hyperglycemic state (HHS).',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 35',
    hccV28Weight: 0.452,
    snomedConceptId: '73211009',
    isChronic: true,
  },
  {
    code: 'E11.21',
    shortDesc: 'Type 2 diabetes mellitus with diabetic nephropathy',
    longDesc: 'Type 2 diabetes mellitus with diabetic nephropathy and persistent microalbuminuria.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 37 (Diabetes with Chronic Complications)',
    hccV28Weight: 0.302,
    snomedConceptId: '127013003',
    isChronic: true,
  },
  {
    code: 'E11.22',
    shortDesc: 'Type 2 diabetes mellitus with diabetic chronic kidney disease',
    longDesc: 'Type 2 diabetes mellitus with diabetic chronic kidney disease requiring concurrent coding of CKD stage.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 37',
    hccV28Weight: 0.302,
    snomedConceptId: '127013003',
    isChronic: true,
  },
  {
    code: 'E11.319',
    shortDesc: 'Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema',
    longDesc: 'Type 2 diabetes mellitus with background non-proliferative diabetic retinopathy.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 37',
    hccV28Weight: 0.302,
    snomedConceptId: '4855003',
    isChronic: true,
  },
  {
    code: 'E11.40',
    shortDesc: 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified',
    longDesc: 'Type 2 diabetes mellitus with distal symmetric peripheral polyneuropathy.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 37',
    hccV28Weight: 0.302,
    snomedConceptId: '230572002',
    isChronic: true,
  },
  {
    code: 'E11.51',
    shortDesc: 'Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene',
    longDesc: 'Type 2 diabetes mellitus with diabetic peripheral arterial vascular disease.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 37',
    hccV28Weight: 0.302,
    snomedConceptId: '157141000119108',
    isChronic: true,
  },
  {
    code: 'E11.65',
    shortDesc: 'Type 2 diabetes mellitus with hyperglycemia',
    longDesc: 'Type 2 diabetes mellitus presenting with uncontrolled blood glucose elevation.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 38',
    hccV28Weight: 0.165,
    snomedConceptId: '73211009',
    isChronic: true,
  },
  {
    code: 'E11.69',
    shortDesc: 'Type 2 diabetes mellitus with other specified complication',
    longDesc: 'Type 2 diabetes mellitus with specified diabetic skin, bone, or neuropathic complications.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 37',
    hccV28Weight: 0.302,
    snomedConceptId: '73211009',
    isChronic: true,
  },
  {
    code: 'E11.9',
    shortDesc: 'Type 2 diabetes mellitus without complications',
    longDesc: 'Type 2 diabetes mellitus without documentation of secondary complications.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E08-E13',
    hccV28Category: 'HCC 38',
    hccV28Weight: 0.165,
    snomedConceptId: '44054006',
    isChronic: true,
  },
  {
    code: 'E66.01',
    shortDesc: 'Morbid (severe) obesity due to excess calories',
    longDesc: 'Morbid obesity with BMI >= 40.0 kg/m2 or BMI >= 35.0 with severe obesity-related conditions.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E65-E68',
    hccV28Category: 'HCC 48 (Morbid Obesity)',
    hccV28Weight: 0.252,
    snomedConceptId: '238136002',
    isChronic: true,
  },
  {
    code: 'E78.00',
    shortDesc: 'Pure hypercholesterolemia, unspecified',
    longDesc: 'Primary hypercholesterolemia / elevated LDL cholesterol.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '13644009',
    isChronic: true,
  },
  {
    code: 'E78.2',
    shortDesc: 'Mixed hyperlipidemia',
    longDesc: 'Combined hyperlipidemia with concurrent elevation of serum cholesterol and triglycerides.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '390952000',
    isChronic: true,
  },
  {
    code: 'E78.5',
    shortDesc: 'Hyperlipidemia, unspecified',
    longDesc: 'Dyslipidemia / hyperlipidemia, unspecified.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '55822004',
    isChronic: true,
  },
  {
    code: 'E87.1',
    shortDesc: 'Hypo-osmolality and hyponatremia',
    longDesc: 'Serum sodium < 135 mEq/L (e.g. SIADH, hypovolemic, or hypervolemic hyponatremia).',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '89627008',
    isChronic: false,
  },
  {
    code: 'E87.20',
    shortDesc: 'Acidosis, unspecified',
    longDesc: 'Metabolic or respiratory acidosis with arterial pH < 7.35.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '59455009',
    isChronic: false,
  },
  {
    code: 'E87.5',
    shortDesc: 'Hyperkalemia',
    longDesc: 'Serum potassium > 5.0 mEq/L with risk of cardiac conduction abnormalities and peaked T waves.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '14140009',
    isChronic: false,
  },
  {
    code: 'E87.6',
    shortDesc: 'Hypokalemia',
    longDesc: 'Serum potassium < 3.5 mEq/L with risk of ventricular arrhythmias and muscle weakness.',
    chapterNumber: 4,
    chapterTitle: 'Endocrine, nutritional and metabolic diseases',
    blockRange: 'E70-E88',
    snomedConceptId: '43339004',
    isChronic: false,
  },
];
