/**
 * Realistic Clinical Seed Data for MediCore HealthOS
 */

import type {
  PatientRecord,
  VitalSignRecord,
  ClinicalEncounter,
  PrescriptionRecord,
  LabOrderRecord,
  TelehealthSessionRecord,
  SuperbillClaimRecord,
} from './types.ts';
import type { AllergyRecord } from '../clinical/allergyEngine.ts';

export const SEED_PATIENTS: PatientRecord[] = [
  {
    id: 'PAT-001',
    mrn: 'MRN-849201',
    fullName: 'Eleanor Vance',
    dob: '1955-04-12',
    gender: 'FEMALE',
    ssnMasked: '***-**-4912',
    phone: '(555) 234-8910',
    email: 'eleanor.vance@example.com',
    bloodType: 'O+',
    address: {
      street: '742 Evergreen Terrace',
      city: 'Boston',
      state: 'MA',
      zip: '02115',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Thomas Vance',
      relationship: 'Son',
      phone: '(555) 987-1234',
    },
    insurance: {
      providerName: 'Blue Cross Blue Shield Medicare Advantage',
      policyNumber: 'BCBS-MA-9920194',
      groupNumber: 'GRP-8812',
      subscriberName: 'Eleanor Vance',
      copayAmountUsd: 25.0,
      deductibleRemainingUsd: 150.0,
      coinsurancePercent: 20,
    },
    status: 'ACTIVE',
    primaryPhysicianId: 'DOC-101',
    primaryPhysicianName: 'Dr. Sarah Mitchell, MD',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2026-02-15T14:30:00Z',
  },
  {
    id: 'PAT-002',
    mrn: 'MRN-910283',
    fullName: 'Marcus Brody',
    dob: '1981-09-23',
    gender: 'MALE',
    ssnMasked: '***-**-8201',
    phone: '(555) 345-6789',
    email: 'm.brody@example.com',
    bloodType: 'A+',
    address: {
      street: '1204 Beacon Street, Apt 4B',
      city: 'Brookline',
      state: 'MA',
      zip: '02446',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Clara Brody',
      relationship: 'Spouse',
      phone: '(555) 345-6790',
    },
    insurance: {
      providerName: 'UnitedHealthcare Choice Plus PPO',
      policyNumber: 'UHC-99281048',
      groupNumber: 'GRP-5541',
      subscriberName: 'Marcus Brody',
      copayAmountUsd: 35.0,
      deductibleRemainingUsd: 600.0,
      coinsurancePercent: 15,
    },
    status: 'ADMITTED',
    primaryPhysicianId: 'DOC-101',
    primaryPhysicianName: 'Dr. Sarah Mitchell, MD',
    createdAt: '2025-05-14T11:20:00Z',
    updatedAt: '2026-02-28T09:15:00Z',
  },
  {
    id: 'PAT-003',
    mrn: 'MRN-637192',
    fullName: 'Sophia Patel',
    dob: '1998-11-04',
    gender: 'FEMALE',
    ssnMasked: '***-**-3341',
    phone: '(555) 456-7890',
    email: 'sophia.patel@example.com',
    bloodType: 'B+',
    address: {
      street: '88 Commonwealth Avenue',
      city: 'Cambridge',
      state: 'MA',
      zip: '02138',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Aarav Patel',
      relationship: 'Brother',
      phone: '(555) 456-7899',
    },
    insurance: {
      providerName: 'Aetna Open Choice PPO',
      policyNumber: 'AET-4432190',
      groupNumber: 'GRP-1092',
      subscriberName: 'Sophia Patel',
      copayAmountUsd: 20.0,
      deductibleRemainingUsd: 0.0,
      coinsurancePercent: 10,
    },
    status: 'ACTIVE',
    primaryPhysicianId: 'DOC-101',
    primaryPhysicianName: 'Dr. Sarah Mitchell, MD',
    createdAt: '2025-08-19T10:00:00Z',
    updatedAt: '2026-01-20T16:45:00Z',
  },
  {
    id: 'PAT-004',
    mrn: 'MRN-448291',
    fullName: 'Liam Rodriguez',
    dob: '2018-06-15',
    gender: 'MALE',
    ssnMasked: '***-**-1190',
    phone: '(555) 567-8901',
    email: 'maria.rodriguez.parent@example.com',
    bloodType: 'A-',
    address: {
      street: '310 Huntington Avenue',
      city: 'Boston',
      state: 'MA',
      zip: '02115',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Maria Rodriguez',
      relationship: 'Mother',
      phone: '(555) 567-8901',
    },
    insurance: {
      providerName: 'MassHealth Standard / Medicaid',
      policyNumber: 'MH-10293847',
      groupNumber: 'STATE-MA',
      subscriberName: 'Liam Rodriguez',
      copayAmountUsd: 0.0,
      deductibleRemainingUsd: 0.0,
      coinsurancePercent: 0,
    },
    status: 'ACTIVE',
    primaryPhysicianId: 'DOC-101',
    primaryPhysicianName: 'Dr. Sarah Mitchell, MD',
    createdAt: '2025-10-02T13:10:00Z',
    updatedAt: '2026-02-10T11:00:00Z',
  },
];

export const SEED_ALLERGIES: AllergyRecord[] = [
  {
    id: 'ALL-001',
    patientId: 'PAT-001',
    allergen: 'Aspirin',
    category: 'MEDICATION',
    reaction: 'Bronchospasm and Urticaria (Hives)',
    severity: 'SEVERE',
    onsetYear: 2012,
  },
  {
    id: 'ALL-002',
    patientId: 'PAT-003',
    allergen: 'Penicillin',
    category: 'MEDICATION',
    reaction: 'Anaphylaxis / Laryngeal Edema',
    severity: 'LIFE_THREATENING',
    onsetYear: 2015,
  },
  {
    id: 'ALL-003',
    patientId: 'PAT-003',
    allergen: 'Sulfa drugs',
    category: 'MEDICATION',
    reaction: 'Maculopapular Rash',
    severity: 'MODERATE',
    onsetYear: 2018,
  },
];

export const SEED_VITALS: VitalSignRecord[] = [
  {
    id: 'VIT-001',
    patientId: 'PAT-001',
    encounterId: 'ENC-001',
    recordedAt: '2026-02-28T08:30:00Z',
    recordedBy: 'NURSE-202',
    recordedByName: 'Robert Vance, RN',
    systolicBP: 138,
    diastolicBP: 84,
    heartRate: 74,
    respiratoryRate: 16,
    spO2: 97,
    temperatureCelsius: 36.8,
    bloodGlucoseMgDl: 142,
    painScale: 2,
    supplementalOxygen: false,
    consciousness: 'ALERT',
    news2Score: 0,
    news2RiskLevel: 'LOW',
  },
  {
    id: 'VIT-002',
    patientId: 'PAT-002',
    encounterId: 'ENC-002',
    recordedAt: '2026-02-28T09:00:00Z',
    recordedBy: 'NURSE-202',
    recordedByName: 'Robert Vance, RN',
    systolicBP: 188,
    diastolicBP: 108,
    heartRate: 118,
    respiratoryRate: 24,
    spO2: 93,
    temperatureCelsius: 37.4,
    bloodGlucoseMgDl: 198,
    painScale: 8,
    supplementalOxygen: true,
    consciousness: 'ALERT',
    news2Score: 8,
    news2RiskLevel: 'HIGH',
  },
];

export const SEED_ENCOUNTERS: ClinicalEncounter[] = [
  {
    id: 'ENC-001',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    physicianId: 'DOC-101',
    physicianName: 'Dr. Sarah Mitchell, MD',
    encounterType: 'OUTPATIENT',
    status: 'IN_PROGRESS',
    startedAt: '2026-02-28T08:30:00Z',
    chiefComplaint: 'Quarterly management for Type 2 Diabetes and CKD; routine medication review.',
    esiLevel: 4,
    soapNote: {
      subjective: 'Patient reports feeling well overall. Complains of occasional bilateral knee stiffness in morning.',
      objective: 'BP 138/84, HR 74, RR 16, SpO2 97%. Well-appearing elderly female in no acute distress.',
      assessment: '1. Type 2 Diabetes Mellitus with CKD (E11.22)\n2. Essential Hypertension (I10)\n3. Paroxysmal Atrial Fibrillation (I48.0)',
      plan: '1. Continue Metformin 500mg BID and Lisinopril 20mg daily.\n2. Repeat Comprehensive Metabolic Panel & HbA1c.\n3. Follow up in 3 months.',
      primaryIcd10: 'E11.22',
      primaryDiagnosisDesc: 'Type 2 diabetes with diabetic chronic kidney disease',
    },
  },
  {
    id: 'ENC-002',
    patientId: 'PAT-002',
    patientName: 'Marcus Brody',
    physicianId: 'DOC-101',
    physicianName: 'Dr. Sarah Mitchell, MD',
    encounterType: 'EMERGENCY',
    status: 'IN_PROGRESS',
    startedAt: '2026-02-28T09:00:00Z',
    chiefComplaint: 'Acute substernal chest pressure radiating to left jaw; diaphoresis and dyspnea.',
    esiLevel: 2,
    admittedToRoom: 'ED-Trauma Bay 2',
    soapNote: {
      subjective: '45-year-old male presents with 45 minutes of crushing retrosternal chest pain (8/10). Denies prior cardiac history.',
      objective: 'BP 188/108, HR 118, RR 24, SpO2 93% on room air -> 98% on 2L nasal cannula. Diaphoretic, anxious.',
      assessment: '1. Acute Coronary Syndrome / Suspected NSTEMI (I25.10)\n2. Hypertensive Crisis (I10)',
      plan: '1. Immediate 12-lead ECG, STAT Troponin-I and CBC/BMP.\n2. Aspirin 325mg chewed, Nitroglycerin sublingual, Heparin drip bolus.\n3. Cardiology consult on standby.',
      primaryIcd10: 'I25.10',
      primaryDiagnosisDesc: 'Atherosclerotic heart disease of native coronary artery',
    },
  },
];

export const SEED_PRESCRIPTIONS: PrescriptionRecord[] = [
  {
    id: 'RX-001',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    prescribedById: 'DOC-101',
    prescribedByName: 'Dr. Sarah Mitchell, MD',
    encounterId: 'ENC-001',
    medicationName: 'Lisinopril',
    rxNormCode: '314076',
    dosage: '20mg',
    frequency: 'Once daily in the morning',
    route: 'Oral',
    quantity: 90,
    refillsRemaining: 3,
    status: 'ACTIVE',
    prescribedAt: '2026-01-15T10:00:00Z',
    instructions: 'Take one tablet by mouth daily for blood pressure control.',
  },
  {
    id: 'RX-002',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    prescribedById: 'DOC-101',
    prescribedByName: 'Dr. Sarah Mitchell, MD',
    encounterId: 'ENC-001',
    medicationName: 'Metformin HCl',
    rxNormCode: '860975',
    dosage: '500mg',
    frequency: 'Twice daily with meals',
    route: 'Oral',
    quantity: 180,
    refillsRemaining: 2,
    status: 'ACTIVE',
    prescribedAt: '2026-01-15T10:00:00Z',
    instructions: 'Take with food to minimize gastrointestinal upset.',
  },
  {
    id: 'RX-003',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    prescribedById: 'DOC-101',
    prescribedByName: 'Dr. Sarah Mitchell, MD',
    encounterId: 'ENC-001',
    medicationName: 'Warfarin Sodium',
    rxNormCode: '855332',
    dosage: '5mg',
    frequency: 'Once daily at bedtime',
    route: 'Oral',
    quantity: 30,
    refillsRemaining: 1,
    status: 'ACTIVE',
    prescribedAt: '2026-02-01T11:00:00Z',
    instructions: 'Maintain target INR 2.0-3.0 for Atrial Fibrillation stroke prevention.',
    warningFlags: ['Requires monthly INR monitoring', 'Interacts strongly with Aspirin and NSAIDs'],
  },
];

export const SEED_LAB_ORDERS: LabOrderRecord[] = [
  {
    id: 'LAB-ORD-001',
    orderNumber: 'ORD-20260228-001',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    orderedById: 'DOC-101',
    orderedByName: 'Dr. Sarah Mitchell, MD',
    encounterId: 'ENC-001',
    panelName: 'Comprehensive Metabolic Panel (CMP)',
    specimenType: 'SERUM',
    specimenBarcode: 'BC-990281-SER',
    status: 'FINALIZED',
    orderedAt: '2026-02-28T08:45:00Z',
    collectedAt: '2026-02-28T08:50:00Z',
    finalizedAt: '2026-02-28T09:30:00Z',
    tests: [
      { testCode: 'GLU', testName: 'Glucose', loincCode: '2345-7', resultValue: 138, resultUnit: 'mg/dL', referenceRangeLow: 70, referenceRangeHigh: 99, interpretation: 'HIGH', isCriticalAlert: false },
      { testCode: 'BUN', testName: 'Blood Urea Nitrogen', loincCode: '3094-0', resultValue: 24, resultUnit: 'mg/dL', referenceRangeLow: 7, referenceRangeHigh: 20, interpretation: 'HIGH', isCriticalAlert: false },
      { testCode: 'CREAT', testName: 'Creatinine', loincCode: '2160-0', resultValue: 1.4, resultUnit: 'mg/dL', referenceRangeLow: 0.5, referenceRangeHigh: 1.1, interpretation: 'HIGH', isCriticalAlert: false },
      { testCode: 'NA', testName: 'Sodium', loincCode: '2951-2', resultValue: 139, resultUnit: 'mmol/L', referenceRangeLow: 135, referenceRangeHigh: 145, interpretation: 'NORMAL', isCriticalAlert: false },
      { testCode: 'K', testName: 'Potassium', loincCode: '2823-3', resultValue: 4.6, resultUnit: 'mmol/L', referenceRangeLow: 3.5, referenceRangeHigh: 5.1, interpretation: 'NORMAL', isCriticalAlert: false },
      { testCode: 'EGFR', testName: 'eGFR (CKD-EPI 2021)', loincCode: '98979-8', resultValue: 42, resultUnit: 'mL/min/1.73m²', referenceRangeLow: 60, referenceRangeHigh: 120, interpretation: 'LOW', isCriticalAlert: false },
    ],
  },
  {
    id: 'LAB-ORD-002',
    orderNumber: 'ORD-20260228-002',
    patientId: 'PAT-002',
    patientName: 'Marcus Brody',
    orderedById: 'DOC-101',
    orderedByName: 'Dr. Sarah Mitchell, MD',
    encounterId: 'ENC-002',
    panelName: 'STAT Cardiac Biomarkers & Troponin',
    specimenType: 'WHOLE_BLOOD',
    specimenBarcode: 'BC-990282-BLD',
    status: 'FINALIZED',
    orderedAt: '2026-02-28T09:05:00Z',
    collectedAt: '2026-02-28T09:10:00Z',
    finalizedAt: '2026-02-28T09:25:00Z',
    tests: [
      { testCode: 'TROP_I', testName: 'Troponin I, High-Sensitivity', loincCode: '89579-7', resultValue: 0.18, resultUnit: 'ng/mL', referenceRangeLow: 0.0, referenceRangeHigh: 0.04, interpretation: 'CRITICAL_HIGH', isCriticalAlert: true },
      { testCode: 'CK_MB', testName: 'Creatine Kinase-MB', loincCode: '2039-6', resultValue: 14.2, resultUnit: 'ng/mL', referenceRangeLow: 0.0, referenceRangeHigh: 4.9, interpretation: 'HIGH', isCriticalAlert: false },
    ],
    technicianNotes: 'STAT CRITICAL ALERT: High-sensitivity Troponin I significantly elevated above 99th percentile. Verified with repeat run and communicated to Dr. Mitchell via critical pager protocol at 09:26.',
  },
];

export const SEED_TELEHEALTH_SESSIONS: TelehealthSessionRecord[] = [
  {
    id: 'TEL-001',
    sessionRoomCode: 'MEDICORE-ROOM-VIRTUAL-881',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    physicianId: 'DOC-101',
    physicianName: 'Dr. Sarah Mitchell, MD',
    scheduledTime: '2026-03-05T14:00:00Z',
    status: 'SCHEDULED',
    durationMinutes: 30,
    consultationSummary: 'Virtual Telehealth Follow-up on blood pressure log and lab results review.',
  },
];

export const SEED_SUPERBILLS: SuperbillClaimRecord[] = [
  {
    id: 'CLM-001',
    claimNumber: 'CLM-202602-0089',
    encounterId: 'ENC-001',
    patientId: 'PAT-001',
    patientName: 'Eleanor Vance',
    providerNpi: '1942857291',
    providerName: 'Dr. Sarah Mitchell, MD',
    dosDate: '2026-02-28',
    primaryDiagnosisCode: 'E11.22',
    secondaryDiagnosisCodes: ['I10', 'I48.0'],
    lineItems: [
      { cptCode: '99214', description: 'Office visit established patient, moderate MDM', units: 1, unitPriceUsd: 195.0, totalChargeUsd: 195.0 },
      { cptCode: '80053', description: 'Comprehensive Metabolic Panel (CMP)', units: 1, unitPriceUsd: 45.0, totalChargeUsd: 45.0 },
      { cptCode: '83036', description: 'Hemoglobin A1c', units: 1, unitPriceUsd: 35.0, totalChargeUsd: 35.0 },
    ],
    totalBilledUsd: 275.0,
    insuranceAllowedUsd: 220.0,
    insurancePaidUsd: 156.0,
    patientCopayUsd: 25.0,
    patientCoinsuranceUsd: 39.0,
    patientBalanceDueUsd: 64.0,
    claimStatus: 'ADJUDICATED',
    adjudicationDate: '2026-02-28T10:00:00Z',
  },
];
